name: CI/CD Workflow

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository's code

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'   # Specify Java 17 version
        distribution: 'temurin'  # Use Temurin (Adoptium distribution)

    - name: Build with Maven
      run: mvn clean install -DskipTests=true  # Build the project, skip tests (since you don't have tests)

    - name: Build Spring Boot application
      run: mvn package -DskipTests=true  # Create the .jar file without running tests


    - name: List target directory
      run: ls -al target/  # List contents of target folder to check if JAR is there

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v2
      with:
        name: demo-jar
        path: target/demo-0.0.1-SNAPSHOT.jar
